//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst_EntityDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentAddresses = new HashSet<StudentAddress>();
        }
    
        public int StudentId { get; set; }
        [Display(Name = "First Name")]
        [MinLength(6,ErrorMessage ="First name must be of min 6 chars")]
        [Required(ErrorMessage ="First Name is Manadory")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last Name is Manadory")]

        public string LastName { get; set; }
        
        [Display(Name ="Standard")]
        public Nullable<int> StandardId { get; set; }
        [Display(Name = "Course")]
        public Nullable<int> CourseId { get; set; }

        //[]
        //[Display(Name = "Course")]
        public virtual Course Course { get; set; }
        //[Display(Name = "Standard")]
        public virtual Standard Standard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAddress> StudentAddresses { get; set; }
    }
}
